name: "The Natural Products Atlas"
overview: "The Natural Products Atlas is a database of all small molecules discovered from bacteria and fungi. It is designed to provide a central repository for all naturally occuring microbial compounds as a resource for researchers in the area of natural products science. https://www.npatlas.org/faq"
statistics:
  - category: "Compounds (TODO: BioLinkと対応)"
    number: 33372
  - category: "Bacterial Compounds (TODO: BioLinkと対応)"
    number: 13068
  - category: "Fungal Compounds (TODO: BioLinkと対応)"
    number: 20304
  - category: "Clusters (TODO: BioLinkと対応)"
    number: 9806
  - category: "Nodes (TODO: BioLinkと対応)"
    number: 6540
  - category: "Bacterial Genera (TODO: BioLinkと対応)"
    number: 378
  - category: "Fungal Genera (TODO: BioLinkと対応)"
    number: 822
category: "secondary"
sources:
  - "各レコードは論文から取得しているっぽい、その場合どう書くか。"
related_articles:
  - doi: "10.1093/nar/gkab941"
  - doi: "10.1021/acscentsci.9b00806"
maintainers:
  - name: "Linington Research Group in the Department of Chemistry at Simon Fraser University in Vancouver, Canada"
    contact: "https://www.npatlas.org/contact"
license: "CC BY 4.0"
versions:
    - number: "v2023_06"
external_links:
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "compound_inchikey"
    xref: "InChI"
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "original_reference_doi"
    xref: "DOI"
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "original_reference_pmid"
    xref: "PubMed"
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "mibig_ids"
    xref: "MIBiG"
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "gnps_ids"
    xref: "GNPS"
  - file_name: "NPAtlas_download_2023_06.tsv"
    file_type: "tsv"
    accessor: "npmrd_ids"
    xref: "NP-MRD"






